### PR TITLE
edit tabs to be scrollable

### LINKED ISSUE #106: Handle tab overflow
**What's missing? Please describe your flow and where this feature will help.**
Today there's a hard coded limitation of up to 3 tabs because the ui can handle tabbar overflow 

**Additional context**
Disabling the add button after three is done at `Gate.open()`

### PR DESCRIPTION
**Pull request by iamrekas**
Closes #106 
Fix CSS with adding flex box to make unlimited max tabs count. Invisible scroll make on touch screen possibility to select tab.

### CODE REVIEW

**Review by daonb — CHANGES_REQUESTED** [review]
Thanks for the PR! x-scrolling indeed work but there are two things that don't:

1. tabs should be evenly distributed  just like on the safari. when only one tab it should take the entire bar when two each half, etc. If you need js to do it you can change the creations on `nameE` in open() at src/window.js
image
2. Arrow should be displayed when the bar overflows

**Review by daonb — CHANGES_REQUESTED** [review]
Thanks for the PR! x-scrolling works but there are to a couple of things that need changing: 

1. tabs should be evenly distributed  just like on the safari. when only one tab it should take the entire bar when two each half, etc. If you need js to do it you can change the creations on `nameE` in open() at src/window.js
image
2. Arrows should be displayed at the edges of the bar when it overflows so the user knows he can scroll.

**Comment by iamrekas** [comment]
@daonb okey, i will do it in this few days

**Comment by daonb** [comment]
@iamrekas I appreciate this. I've got just less than a month till 1.0 and this is one of the key features still open. 

I need all the help I can get and I hope you can find the time for it in the next 10 days. If you can't just let me know and I'll take over. If you do find the time, please check out #124 , it should be simple to close that as well.

**Comment by daonb** [comment]
I'm sorry but I couldn't wait any longer and coded to myself. 

Hope we'll have better luck next time.

**Pull request closed without merging**
